import os,json,time,secrets,hashlib,io,zipfile,csv,re
from functools import wraps
from pathlib import Path
from flask import Flask,request,jsonify,g,send_file
from werkzeug.security import generate_password_hash,check_password_hash
from werkzeug.exceptions import HTTPException
from sqlalchemy import select,func,delete,update,or_
from sqlalchemy.exc import IntegrityError
from sqlalchemy.orm.exc import StaleDataError
from .db import *
from .config import default_files
from .agent_bridge import register_agent_bridge,device_allowed
from .distribution import register_distribution
from .fiscal import *
from .storage import LocalStorageProvider
from .providers import extract_pdf,validate_pdf,ProviderPending,ProviderFailure
from .certificates import inspect_a1
from .document_management import register_management,verify_deletion_password
from .fiscal_history import register_history, fiscal_statuses
from .client_capture import register_client_capture
from .fiscal_channels import register_fiscal_channels
from .nfce import register_nfce
from .manifest_automation import ScienceCandidate
from .version import VERSION, REVISION

def create_app(database_url=None,data_dir=None,testing=False):
    app=Flask(__name__,static_folder='static',static_url_path='/static')
    app.config.update(MAX_CONTENT_LENGTH=64*1024*1024,TESTING=testing)
    engine,Session=init_db(database_url)
    app.config['ALLOW_SIGNUP']=os.getenv('DOCPRONTO_ALLOW_SIGNUP','1')=='1'
    app.session_factory=Session;app.engine=engine
    storage=LocalStorageProvider(data_dir or os.getenv('DATA_DIR',default_files()));app.storage=storage
    # A random bootstrap token is generated by setup.py, never default credentials.
    secure=os.getenv('COOKIE_SECURE','0')=='1'
    def fail(message,status=400):return jsonify(error=message),status
    def digest(t):return hashlib.sha256(t.encode()).hexdigest()
    @app.before_request
    def guard():
        if request.content_length and request.content_length>64*1024*1024:return fail('Upload excede 64 MB.',413)
        if not testing and request.host.split(':')[0] not in os.getenv('ALLOWED_HOSTS','localhost,127.0.0.1').split(','):return fail('Host não autorizado.',400)
        if request.method not in ('GET','HEAD','OPTIONS'):
            origin=request.headers.get('Origin')
            if origin and origin!=request.host_url.rstrip('/'):return fail('Origem não autorizada.',403)
        if request.path.startswith('/api/') and request.method not in ('GET','HEAD','OPTIONS') and request.is_json:
            if not isinstance(request.get_json(silent=True),dict):return fail('Corpo JSON inválido.',400)
        g.s=Session()
        if not request.path.startswith('/api/') or request.path in ('/api/login','/api/bootstrap','/api/status','/api/signup') or re.fullmatch(r'/api/invites/[A-Za-z0-9_-]{20,100}(?:/accept)?',request.path) or request.path.startswith('/api/agent/'):return
        token=request.cookies.get('docpronto_session','')
        session=g.s.get(Login,digest(token)) if token else None
        if not session or session.expires<time.time():return fail('Entre para continuar.',401)
        g.user=g.s.get(User,session.user_id);g.login=session
        if request.method not in ('GET','HEAD','OPTIONS') and not secrets.compare_digest(request.headers.get('X-CSRF-Token',''),session.csrf):return fail('Sessão expirada ou proteção CSRF inválida.',403)
    @app.teardown_request
    def close(error):
        if hasattr(g,'s'):g.s.close()
    @app.after_request
    def headers(response):
        response.headers['X-Content-Type-Options']='nosniff';response.headers['X-Frame-Options']='DENY'
        response.headers['Referrer-Policy']='no-referrer'
        response.headers['Content-Security-Policy']="default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data: blob:; media-src 'self' blob:; object-src 'none'; frame-ancestors 'none'; base-uri 'self'; form-action 'self'"
        response.headers['Cache-Control']='no-store'
        if secure:response.headers['Strict-Transport-Security']='max-age=31536000'
        return response
    @app.errorhandler(FiscalError)
    @app.errorhandler(ValueError)
    def bad(ex):return fail(str(ex),400)
    @app.errorhandler(StaleDataError)
    @app.errorhandler(IntegrityError)
    def conflict(ex):
        g.s.rollback();return fail('Registro duplicado ou alteração concorrente. Atualize a listagem.',409)
    @app.errorhandler(Exception)
    def unexpected(ex):
        if isinstance(ex,HTTPException):return fail(ex.description,ex.code)
        app.logger.error('Falha interna: %s',type(ex).__name__)
        return fail('Falha interna. Nenhum sucesso foi confirmado; consulte a auditoria.',500)
    def payload():
        d=request.get_json(silent=True)
        if not isinstance(d,dict):raise ValueError('Corpo JSON inválido.')
        return d
    def company(cid,write=False,admin=False):
        if not isinstance(cid,str) or not cid or len(cid)>64:raise FiscalError('Selecione um cadastro fiscal válido.')
        co=g.s.get(Company,cid);member=g.s.get(Member,(g.user.id,cid))
        if not co or not member:raise FiscalError('Empresa não disponível para este usuário.')
        if (write and member.role=='viewer') or (admin and member.role!='admin'):raise FiscalError('Perfil sem permissão para esta ação.')
        return co
    def document(did,write=False):
        d=g.s.get(Document,did)
        if not d:raise FiscalError('Documento não encontrado.')
        company(d.company_id,write);return d
    def view(d):
        states=getattr(g,'document_fiscal_states',None)
        if states is None:
            states=fiscal_statuses(g.s,storage,d.company_id,[d.key])
        return {'id':d.id,'key':d.key,'status':d.status,'fiscal_status':states.get(d.key,'unknown'),'source':d.source,'data':json.loads(d.data),'error':d.error,'has_pdf':bool(d.pdf),'has_xml':bool(d.xml),'has_draft':bool(d.draft),'created':d.created,'updated':d.updated}
    def audit(action,cid=None,details='',doc=None):log(g.s,cid,g.user.id,action,details,doc)
    def limited(key,limit=15):
        now=time.time();bucket=f'{key}:{int(now//300)}'
        record=g.s.get(RateBucket,bucket)
        if record is None:
            g.s.add(RateBucket(key=bucket,expires=now+600,count=1));g.s.flush()
        else:
            updated=g.s.execute(update(RateBucket).where(RateBucket.key==bucket,RateBucket.count<limit).values(count=RateBucket.count+1)).rowcount
            if not updated:return True
        g.s.execute(delete(RateBucket).where(RateBucket.expires<now));g.s.commit();return False
    @app.get('/')
    def index():return app.send_static_file('index.html')
    @app.get('/api/status')
    def status():
        result=dict(needs_setup=g.s.scalar(select(func.count()).select_from(User))==0,version=VERSION,revision=REVISION,mode='self-hosted',allow_signup=app.config['ALLOW_SIGNUP'])
        if os.getenv('DOCPRONTO_LOCAL_INSTANCE'):
            result.update(mode='windows-local',local_instance=os.environ['DOCPRONTO_LOCAL_INSTANCE'])
        return jsonify(result)
    @app.post('/api/bootstrap')
    def bootstrap():
        d=payload()
        if limited('setup:'+request.remote_addr,8):return fail('Muitas tentativas; aguarde 5 minutos.',429)
        if g.s.scalar(select(func.count()).select_from(User)):return fail('Instalação já configurada.',409)
        expected=os.getenv('SETUP_TOKEN','')
        if not expected or not secrets.compare_digest(d.get('setup_token',''),expected):return fail('Token de instalação inválido. Use o token gerado pelo instalador.',403)
        email=d.get('email','').strip().lower();password=d.get('password','')
        if '@' not in email or len(email)>250 or len(password)<12:raise ValueError('Informe e-mail e senha com no mínimo 12 caracteres.')
        # Singleton insert serializes concurrent bootstrap requests.
        g.s.add(Setting(key='bootstrap_completed',value='1'));g.s.flush()
        g.s.add(User(email=email,password=generate_password_hash(password),role='superadmin'))
        g.s.commit();return jsonify(ok=True)
    @app.post('/api/login')
    def login():
        d=payload()
        if limited('login:'+request.remote_addr):return fail('Muitas tentativas. Aguarde 5 minutos.',429)
        u=g.s.scalar(select(User).where(User.email==str(d.get('email','')).lower().strip()))
        if not u or not check_password_hash(u.password,str(d.get('password',''))):return fail('E-mail ou senha incorretos.',401)
        token=secrets.token_urlsafe(48);csrf=secrets.token_urlsafe(32)
        g.s.execute(delete(Login).where(Login.expires<time.time()))
        g.s.add(Login(token_hash=digest(token),user_id=u.id,expires=time.time()+8*3600,csrf=csrf));log(g.s,None,u.id,'login');g.s.commit()
        res=jsonify(ok=True,csrf=csrf);res.set_cookie('docpronto_session',token,httponly=True,secure=secure,samesite='Strict',max_age=8*3600);return res
    @app.post('/api/logout')
    def logout():
        g.s.delete(g.login);g.s.commit();res=jsonify(ok=True);res.delete_cookie('docpronto_session');return res
    @app.get('/api/me')
    def me():return jsonify(email=g.user.email,role=g.user.role,csrf=g.login.csrf)
    def owned_provider(pid):
        from .teams import provider_role,lock_provider
        provider=lock_provider(g.s,pid)
        if not provider or provider_role(g.s,g.user,pid)!='admin':
            raise ValueError('Organização indisponível para administração.')
        return provider
    def entity_name(d):
        name=str(d.get('name','')).strip()
        if not 2<=len(name)<=200:raise ValueError('Informe um nome entre 2 e 200 caracteres.')
        return name
    @app.get('/api/organization')
    def organization():
        from .teams import ProviderMember,provider_role
        team_ids=select(ProviderMember.provider_id).where(ProviderMember.user_id==g.user.id)
        visible_providers=select(ServiceProvider.id).where(or_(ServiceProvider.owner_id==g.user.id,ServiceProvider.id.in_(team_ids)))
        allowed=select(Member.company_id).where(Member.user_id==g.user.id)
        visible_clients=select(ClientRegistration.client_id).where(ClientRegistration.company_id.in_(allowed))
        clients=g.s.scalars(select(Client).where(or_(Client.id.in_(visible_clients),Client.provider_id.in_(visible_providers)))).all()
        providers=g.s.scalars(select(ServiceProvider).where(or_(ServiceProvider.id.in_(visible_providers),ServiceProvider.id.in_([c.provider_id for c in clients])))).all()
        return jsonify(providers=[{'id':p.id,'name':p.name,'can_manage':provider_role(g.s,g.user,p.id)=='admin',
            'documents':list(g.s.scalars(select(ProviderTaxId.document).where(ProviderTaxId.provider_id==p.id))) if provider_role(g.s,g.user,p.id)=='admin' else []} for p in providers],
            clients=[{'id':c.id,'name':c.name,'provider_id':c.provider_id} for c in clients])
    @app.post('/api/providers')
    def create_provider():
        if g.user.role!='superadmin':return fail('Somente o administrador da instalação cadastra prestadoras.',403)
        d=payload();p=ServiceProvider(name=entity_name(d),owner_id=g.user.id);g.s.add(p);g.s.flush()
        audit('prestadora_criada',details=p.id);g.s.commit();return jsonify(id=p.id)
    @app.post('/api/providers/<pid>/documents')
    def provider_document(pid):
        owned_provider(pid);d=payload();tax=digits(d.get('document'))
        if len(tax)!=14 or not validate_tax_id(tax):raise ValueError('Informe um CNPJ válido da prestadora.')
        g.s.add(ProviderTaxId(provider_id=pid,document=tax));audit('cnpj_prestadora_adicionado',details=pid);g.s.commit();return jsonify(ok=True)
    @app.post('/api/clients')
    def create_client():
        d=payload();p=owned_provider(d.get('provider_id'));c=Client(provider_id=p.id,name=entity_name(d))
        g.s.add(c);g.s.flush();audit('cliente_criado',details=c.id);g.s.commit();return jsonify(id=c.id)
    @app.post('/api/clients/<client_id>/registrations')
    def link_registration(client_id):
        d=payload();client=g.s.get(Client,client_id)
        if not client:raise ValueError('Cliente indisponível.')
        owned_provider(client.provider_id)
        co=company(d.get('company_id'),admin=True)
        previous=g.s.get(ClientRegistration,co.id)
        if previous:
            if previous.client_id==client_id:return jsonify(ok=True)
            raise ValueError('CNPJ/CPF já vinculado a outro cliente. Nenhum documento foi movido.')
        if co.organization_id and co.organization_id!=client.provider_id:
            raise ValueError('Não é possível transferir dados entre organizações.')
        co.organization_id=client.provider_id
        from .teams import grant_company_members
        grant_company_members(g.s,co.id,g.s.get(ServiceProvider,client.provider_id))
        g.s.add(ClientRegistration(company_id=co.id,client_id=client_id))
        audit('cadastro_vinculado_cliente',co.id,client_id);g.s.commit();return jsonify(ok=True)
    @app.route('/api/providers/<pid>', methods=['PATCH','DELETE'])
    def edit_provider(pid):
        row=owned_provider(pid)
        if request.method=='PATCH':row.name=entity_name(payload())
        else:
            from .teams import ProviderMember,TeamInvite
            if g.s.scalar(select(Company.id).where(Company.organization_id==pid).limit(1)) or g.s.scalar(select(ProviderMember.user_id).where(ProviderMember.provider_id==pid).limit(1)) or g.s.scalar(select(TeamInvite.id).where(TeamInvite.provider_id==pid).limit(1)):
                raise ValueError('Esta organização tem equipe, convites ou cadastros vinculados.')
            if g.s.scalar(select(Client.id).where(Client.provider_id==pid).limit(1)) or g.s.scalar(select(ProviderTaxId.document).where(ProviderTaxId.provider_id==pid).limit(1)):
                raise ValueError('Remova ou reorganize os clientes e CNPJs próprios antes de excluir a prestadora.')
            g.s.delete(row)
        audit('prestadora_'+request.method.lower(),details=pid);g.s.commit();return jsonify(ok=True)
    @app.delete('/api/providers/<pid>/documents/<tax>')
    def remove_provider_tax(pid,tax):
        owned_provider(pid);row=g.s.get(ProviderTaxId,(pid,tax))
        if not row or row.provider_id!=pid:raise ValueError('CNPJ próprio indisponível.')
        g.s.delete(row);audit('cnpj_proprio_removido',details=pid);g.s.commit();return jsonify(ok=True)
    @app.route('/api/clients/<client_id>', methods=['PATCH','DELETE'])
    def edit_client(client_id):
        row=g.s.get(Client,client_id)
        if not row:raise ValueError('Cliente indisponível.')
        owned_provider(row.provider_id)
        if request.method=='PATCH':row.name=entity_name(payload())
        else:
            if g.s.scalar(select(ClientRegistration.company_id).where(ClientRegistration.client_id==client_id).limit(1)):
                raise ValueError('Desvincule ou transfira os CNPJs/CPFs antes de excluir o cliente.')
            g.s.delete(row)
        audit('cliente_'+request.method.lower(),details=client_id);g.s.commit();return jsonify(ok=True)
    @app.patch('/api/registrations/<coid>/client')
    def correct_registration_client(coid):
        co=company(coid,admin=True);d=payload()
        link=g.s.scalar(select(ClientRegistration).where(ClientRegistration.company_id==coid).with_for_update())
        previous=link.client_id if link else None
        if 'expected_client_id' not in d or d['expected_client_id']!=previous:
            raise ValueError('O vínculo mudou. Atualize a tela antes de continuar.')
        if d.get('confirm_document')!=co.document:raise ValueError('Confirme o CNPJ/CPF para alterar o vínculo.')
        if link:owned_provider(g.s.get(Client,link.client_id).provider_id)
        destination=d.get('client_id')
        if destination:
            client=g.s.get(Client,destination)
            if not client:raise ValueError('Cliente indisponível.')
            owned_provider(client.provider_id)
            if co.organization_id and co.organization_id!=client.provider_id:
                raise ValueError('Não é possível transferir dados entre organizações.')
            co.organization_id=client.provider_id
            from .teams import grant_company_members
            grant_company_members(g.s,co.id,g.s.get(ServiceProvider,client.provider_id))
            if link:link.client_id=client.id
            else:g.s.add(ClientRegistration(company_id=coid,client_id=client.id))
        elif link:g.s.delete(link)
        audit('vinculo_cliente_corrigido',coid,json.dumps({'anterior':previous,'novo':destination}));g.s.commit();return jsonify(ok=True)
    def registration_has_records(coid):
        # Preserve every dependent fiscal/agent record, including extension tables.
        for mapper in Base.registry.mappers:
            model=mapper.class_
            if model in (Member,ClientRegistration,Audit) or not hasattr(model,'company_id'):continue
            if g.s.scalar(select(model.company_id).where(model.company_id==coid).limit(1)):return True
        if g.s.get(Setting,'capture-registration:'+coid):return True
        return False
    def clear_registration_operations(coid):
        from .agent_bridge import AgentDevice,AgentCompanyLink,CompanyCertificate,CertificateTask
        from .distribution import DistributionTask,DistributionState,CaptureBatch,CaptureDispatch,CaptureItem
        from .client_capture import StoredA1
        from .fiscal_history import FiscalArchive
        docs=g.s.scalar(select(func.count()).select_from(Document).where(Document.company_id==coid))
        history=g.s.scalar(select(func.count()).select_from(FiscalArchive).where(FiscalArchive.company_id==coid))
        if docs or history:
            raise ValueError(f'Este CNPJ/CPF ainda possui {docs} documento(s) em Documentos e {history} arquivo(s) no Histórico fiscal. Nenhum arquivo foi apagado.')
        running=g.s.scalar(select(DistributionTask.id).where(DistributionTask.company_id==coid,DistributionTask.state=='running',DistributionTask.expires>time.time()).limit(1))
        if running:raise ValueError('Existe uma consulta em andamento para este CNPJ/CPF. Pare as próximas consultas e aguarde a atual terminar antes de excluir.')
        batches=select(CaptureBatch.id).where(CaptureBatch.company_id==coid)
        tasks=select(DistributionTask.id).where(DistributionTask.company_id==coid)
        g.s.execute(delete(CaptureDispatch).where(or_(CaptureDispatch.batch_id.in_(batches),CaptureDispatch.task_id.in_(tasks))))
        g.s.execute(delete(CaptureItem).where(CaptureItem.batch_id.in_(batches)))
        for model in (CaptureBatch,DistributionTask,DistributionState,CompanyCertificate,StoredA1,AgentCompanyLink):
            g.s.execute(delete(model).where(model.company_id==coid))
        g.s.execute(delete(Setting).where(Setting.key=='capture-registration:'+coid))
        for dev in g.s.scalars(select(AgentDevice).where(AgentDevice.company_id==coid)).all():
            other=g.s.scalar(select(AgentCompanyLink.company_id).where(AgentCompanyLink.device_id==dev.id).order_by(AgentCompanyLink.company_id).limit(1))
            if other:dev.company_id=other
            else:
                g.s.execute(delete(CertificateTask).where(CertificateTask.device_id==dev.id))
                g.s.delete(dev)
        g.s.flush()
    @app.route('/api/registrations/<coid>', methods=['PATCH','DELETE'])
    def edit_registration(coid):
        co=company(coid,admin=True);d=payload()
        if request.method=='PATCH':
            co.name=entity_name(d)
            tax=digits(d.get('document',co.document))
            if not validate_tax_id(tax):raise ValueError('CNPJ/CPF inválido.')
            if tax!=co.document and registration_has_records(coid):
                raise ValueError('Este cadastro já tem registros. Cadastre o CNPJ/CPF correto separadamente; o histórico mantém sua identidade.')
            if g.s.scalar(select(Company.id).where(Company.id!=co.id,Company.organization_id==co.organization_id,Company.document==tax).limit(1)):
                raise ValueError('CNPJ/CPF já cadastrado nesta organização.')
            co.document=tax
        else:
            if d.get('confirm_document')!=co.document:raise ValueError('Confirme o CNPJ/CPF para excluir.')
            if d.get('clear_operations') is not True:raise ValueError('Confirme a remoção das configurações de captura e certificados deste cadastro.')
            link=g.s.get(ClientRegistration,coid)
            if link:owned_provider(g.s.get(Client,link.client_id).provider_id)
            clear_registration_operations(coid)
            g.s.execute(delete(ClientRegistration).where(ClientRegistration.company_id==coid))
            g.s.execute(delete(Member).where(Member.company_id==coid));g.s.delete(co)
        audit('cadastro_fiscal_'+request.method.lower(),coid);g.s.commit();return jsonify(ok=True)
    @app.get('/api/companies')
    def companies():
        rows=g.s.execute(select(Company,Member.role).join(Member,Member.company_id==Company.id).where(Member.user_id==g.user.id)).all()
        result=[]
        for c,r in rows:
            link=g.s.get(ClientRegistration,c.id);client=g.s.get(Client,link.client_id) if link else None
            result.append({'id':c.id,'name':c.name,'document':c.document,'role':r,'client_id':client.id if client else None,'provider_id':c.organization_id or (client.provider_id if client else None)})
        return jsonify(result)
    @app.post('/api/companies')
    def create_company():
        from .teams import grant_company_members
        d=payload();tax=digits(d.get('document'));name=str(d.get('name','')).strip()
        if not validate_tax_id(tax):raise FiscalError('CNPJ/CPF inválido.')
        if not 2<=len(name)<=200:raise ValueError('Nome da empresa inválido.')
        client=None;provider=None
        if d.get('client_id'):
            client=g.s.get(Client,d['client_id'])
            if not client:raise ValueError('Cliente indisponível.')
            provider=owned_provider(client.provider_id)
            if d.get('organization_id') and d['organization_id']!=provider.id:
                raise ValueError('Cliente de outra organização.')
        elif d.get('organization_id'):
            provider=owned_provider(d['organization_id'])
            client=g.s.scalar(select(Client).where(Client.provider_id==provider.id).order_by(Client.id).limit(1))
            if not client:
                client=Client(provider_id=provider.id,name='Cadastros da organização');g.s.add(client);g.s.flush()
        elif g.user.role!='superadmin':
            return fail('Selecione uma organização que você administra.',403)
        organization_id=provider.id if provider else None
        if g.s.scalar(select(Company.id).where(Company.document==tax,Company.organization_id==organization_id).limit(1)):
            raise ValueError('CNPJ/CPF já cadastrado nesta organização.')
        co=Company(name=name,document=tax,organization_id=organization_id);g.s.add(co);g.s.flush()
        if provider:grant_company_members(g.s,co.id,provider)
        else:g.s.add(Member(company_id=co.id,user_id=g.user.id,role='admin'))
        audit('cadastro_fiscal_criado',co.id)
        if client:g.s.add(ClientRegistration(company_id=co.id,client_id=client.id))
        g.s.commit();return jsonify(id=co.id)
    @app.get('/api/users')
    def users():
        cid=request.args.get('company');company(cid,admin=True)
        return jsonify([{'id':u.id,'email':u.email,'role':m.role} for u,m in g.s.execute(select(User,Member).join(Member,Member.user_id==User.id).where(Member.company_id==cid))])
    @app.post('/api/users')
    def create_user():
        d=payload();cid=d.get('company');company(cid,admin=True)
        role=d.get('role');email=str(d.get('email','')).lower().strip();password=str(d.get('password',''))
        if role not in ('admin','operator','viewer') or '@' not in email or len(password)<12:raise ValueError('E-mail, perfil ou senha inválidos.')
        u=g.s.scalar(select(User).where(User.email==email))
        if u:raise ValueError('Usuário já existe. Vinculação entre empresas exige administrador da instalação.')
        u=User(email=email,password=generate_password_hash(password),role='user');g.s.add(u);g.s.flush();g.s.add(Member(company_id=cid,user_id=u.id,role=role));audit('usuario_criado',cid,role);g.s.commit();return jsonify(ok=True)
    @app.get('/api/dashboard')
    def dashboard():
        cid=request.args.get('company');company(cid)
        rows=g.s.execute(select(Document.status,func.count()).where(Document.company_id==cid).group_by(Document.status)).all()
        counts=dict(rows)
        return jsonify(total=sum(counts.values()),counts=counts,pdfs=g.s.scalar(select(func.count()).select_from(Document).where(Document.company_id==cid,Document.pdf.is_not(None))),xmls=g.s.scalar(select(func.count()).select_from(Document).where(Document.company_id==cid,Document.xml.is_not(None))))
    @app.get('/api/documents')
    def list_documents():
        cid=request.args.get('company');company(cid);page=max(1,int(request.args.get('page',1)));size=50
        query=select(Document).where(Document.company_id==cid)
        search=request.args.get('q','')[:200]
        if search:
            safe=search.replace('\\','\\\\').replace('%','\\%').replace('_','\\_')
            query=query.where(or_(Document.key.like('%'+safe+'%',escape='\\'),Document.data.like('%'+safe+'%',escape='\\')))
        if request.args.get('status'):query=query.where(Document.status==request.args['status'])
        total=g.s.scalar(select(func.count()).select_from(query.subquery()))
        docs=g.s.scalars(query.order_by(Document.created.desc(),Document.id).offset((page-1)*size).limit(size)).all()
        g.document_fiscal_states=fiscal_statuses(g.s,storage,cid,{d.key for d in docs})
        return jsonify(items=[view(d) for d in docs],page=page,total=total,pages=max(1,(total+size-1)//size))
    @app.post('/api/keys')
    def add_keys():
        d=payload();cid=d.get('company');company(cid,True)
        text=d.get('keys','')
        if not isinstance(text,str) or len(text)>6000000:raise ValueError('Lista excede 6 MB.')
        lines=[v.strip().strip('"') for v in re.split(r'[\r\n;,]+',text) if v.strip()]
        if len(lines)>100000:raise ValueError('Limite de 100.000 chaves por lote.')
        added=duplicates=0;errors=[];seen=set();valid=[]
        for i,line in enumerate(lines):
            try:key=validate_key(line)
            except FiscalError as ex:
                if len(errors)<200:errors.append({'line':i+1,'error':str(ex)})
                continue
            if key in seen:duplicates+=1;continue
            seen.add(key);valid.append(key)
        for start in range(0,len(valid),500):
            chunk=valid[start:start+500];existing=set(g.s.scalars(select(Document.key).where(Document.company_id==cid,Document.key.in_(chunk))))
            pending=[]
            for key in chunk:
                if key in existing:duplicates+=1;continue
                doc=Document(company_id=cid,key=key,id=uid());g.s.add(doc);pending.append(doc);added+=1
            g.s.flush()
            g.s.add_all([Job(document_id=doc.id) for doc in pending])
            g.s.commit()
        audit('chaves_recebidas',cid,json.dumps({'added':added,'duplicates':duplicates,'invalid':len(lines)-added-duplicates}));g.s.commit()
        return jsonify(added=added,duplicates=duplicates,invalid=len(lines)-added-duplicates,errors=errors)
    def ingest_xml(raw,cid,operation,source='IMPORTED'):
        co=company(cid,True);data=parse_xml(raw,co.document,operation)
        doc=g.s.scalar(select(Document).where(Document.company_id==cid,Document.key==data['key']))
        if doc and doc.xml:
            if json.loads(doc.data).get('sha256')==data['sha256']:return {'id':doc.id,'duplicate':True}
            raise FiscalError('Já existe XML diferente para a mesma chave. Original preservado; revisar antes de substituir.')
        if not doc:doc=Document(id=uid(),company_id=cid,key=data['key']);g.s.add(doc);g.s.flush()
        doc.xml=storage.save(cid,doc.id,raw,'xml');doc.data=json.dumps(data,ensure_ascii=False);doc.source=source;doc.status='concluido';doc.error='';doc.updated=time.time()
        job=g.s.scalar(select(Job).where(Job.document_id==doc.id))
        if job:job.state='completed';job.owner=None;job.lease_until=0
        audit('xml_importado',cid,data['sha256'],doc.id)
        return {'id':doc.id,'key':doc.key,'duplicate':False}
    @app.post('/api/import')
    def import_files():
        cid=request.form.get('company');company(cid,True);operation=request.form.get('operation','auto')
        f=request.files.get('file')
        if not f:raise ValueError('Selecione arquivo XML ou ZIP.')
        raw=f.read();results=[]
        if raw[:2]==b'PK':
            try:z=zipfile.ZipFile(io.BytesIO(raw))
            except zipfile.BadZipFile:raise FiscalError('ZIP inválido.')
            infos=z.infolist()
            if len(infos)>5000 or sum(i.file_size for i in infos)>128*1024*1024:raise FiscalError('Divida o ZIP: limite de 5.000 entradas ou 128 MB descompactados.')
            for entry in infos:
                if entry.is_dir() or not entry.filename.lower().endswith('.xml'):continue
                if entry.compress_type not in (zipfile.ZIP_STORED,zipfile.ZIP_DEFLATED):
                    results.append({'file':entry.filename,'error':'Método de compressão não suportado. Use ZIP comum/Deflate.'});continue
                if entry.file_size>8*1024*1024 or entry.flag_bits&1 or entry.file_size/max(entry.compress_size,1)>200:
                    results.append({'file':entry.filename,'error':'XML excessivo, ZIP cifrado ou taxa de compressão insegura.'});continue
                try:
                    with g.s.begin_nested():item=ingest_xml(z.read(entry),cid,operation)
                    results.append({'file':entry.filename,**item})
                except (FiscalError,IntegrityError,StaleDataError,zipfile.BadZipFile,NotImplementedError,RuntimeError) as ex:results.append({'file':entry.filename,'error':str(ex) if isinstance(ex,FiscalError) else 'Conflito ou arquivo corrompido.'})
            if not results:raise FiscalError('Nenhum XML encontrado no ZIP.')
        else:results.append({'file':f.filename,**ingest_xml(raw,cid,operation)})
        g.s.commit();return jsonify(results=results)
    @app.get('/api/documents/<did>')
    def detail(did):
        doc=document(did);audit('documento_consultado',doc.company_id,doc=did);g.s.commit()
        result=view(doc)
        if doc.draft:result['draft']=json.loads(storage.resolve(doc.draft).read_text())
        result['history']=[{'action':a.action,'details':a.details,'created':a.created} for a in g.s.scalars(select(Audit).where(Audit.document_id==did).order_by(Audit.created.desc()).limit(50))]
        return jsonify(result)
    @app.post('/api/documents/<did>/pdf')
    def upload_pdf(did):
        doc=document(did,True);f=request.files.get('file')
        if not f:raise ValueError('Selecione PDF.')
        raw=f.read(20*1024*1024+1)
        if len(raw)>20*1024*1024 or not raw.startswith(b'%PDF-'):raise ValueError('PDF inválido ou acima de 20 MB.')
        if doc.pdf:raise ValueError('PDF já anexado; arquivo original preservado.')
        try:validate_pdf(raw)
        except (ProviderPending,ProviderFailure) as ex:raise FiscalError(str(ex))
        doc.pdf=storage.save(doc.company_id,did,raw,'pdf');doc.updated=time.time()
        if not doc.xml:
            doc.status='revisao';job=g.s.scalar(select(Job).where(Job.document_id==did))
            if job:job.stage='conversion';job.state='pending';job.available=time.time();job.attempts=0;job.owner=None
            else:g.s.add(Job(document_id=did,stage='conversion'))
        audit('pdf_anexado',doc.company_id,hashlib.sha256(raw).hexdigest(),did);g.s.commit()
        return jsonify(ok=True)
    @app.post('/api/documents/<did>/extract')
    def extract(did):
        doc=document(did,True)
        if not doc.pdf:raise FiscalError('Anexe o PDF primeiro.')
        try:
            from .pdf_engine import extract_invoice
            result=extract_invoice(storage.resolve(doc.pdf),doc.key)
        except (ProviderPending,ProviderFailure) as ex:raise FiscalError(str(ex))
        doc.draft=storage.save(doc.company_id,did,json.dumps(result,ensure_ascii=False).encode(),'json');audit('texto_extraido',doc.company_id,doc=did);g.s.commit();return jsonify(result)
    @app.post('/api/documents/<did>/reconstruct')
    def reconstruct(did):
        doc=document(did,True);d=payload()
        if doc.xml:raise FiscalError('XML existente preservado. Não sobrescrever uma nota importada.')
        if not doc.pdf:raise FiscalError('Anexe o PDF de origem antes de reconstruir.')
        if d.get('confirmed') is not True:raise FiscalError('Confirme a conferência dos dados com o PDF.')
        if d.get('invoice',{}).get('key')!=doc.key:raise FiscalError('Chave da revisão diverge do documento.')
        from .pdf_engine import validate_review
        missing=validate_review(d['invoice'])
        if missing:raise FiscalError('Complete os campos obrigatórios: '+', '.join(missing[:15]))
        persist_draft(doc,d['invoice'])
        co=company(doc.company_id,True);raw,data=build_reconstructed(d['invoice'],co.document)
        doc.xml=storage.save(doc.company_id,did,raw,'xml');doc.source='RECONSTRUCTED';doc.data=json.dumps(data,ensure_ascii=False);doc.status='concluido';doc.error='';doc.updated=time.time()
        job=g.s.scalar(select(Job).where(Job.document_id==did))
        if job:job.state='completed';job.owner=None
        audit('xml_reconstruido_conferido',doc.company_id,data['sha256'],did);g.s.commit();return jsonify(ok=True,data=data)
    @app.post('/api/documents/<did>/approve')
    def approve(did):
        doc=document(did,True)
        if not doc.xml or doc.source!='RECONSTRUCTED':raise FiscalError('Não há reconstrução pendente.')
        if payload().get('confirmed') is not True:raise FiscalError('Confirme a conferência com o PDF.')
        doc.status='concluido';doc.error='';doc.updated=time.time()
        audit('reconstrucao_aprovada',doc.company_id,doc=did);g.s.commit();return jsonify(ok=True)
    @app.get('/api/documents/<did>/download/<kind>')
    def download(did,kind):
        doc=document(did)
        if kind not in ('pdf','xml'):raise FiscalError('Formato inválido.')
        if kind=='xml' and doc.source=='RECONSTRUCTED' and doc.status!='concluido':raise FiscalError('Conferência com PDF pendente antes de exportar o XML reconstruído.')
        path=getattr(doc,kind)
        if not path and kind=='pdf' and doc.xml:
            if doc.source=='RECONSTRUCTED' and doc.status!='concluido':raise FiscalError('Conclua a conferência antes de gerar o espelho.')
            from .document_pdf import render_pdf
            raw=render_pdf(storage.resolve(doc.xml).read_bytes(),doc.source)
            audit('espelho_pdf_gerado',doc.company_id,doc=did);g.s.commit()
            return send_file(io.BytesIO(raw),mimetype='application/pdf',as_attachment=True,download_name=doc.key+'-espelho.pdf')
        if not path:raise FiscalError('Arquivo ainda não disponível.')
        audit('download_'+kind,doc.company_id,doc=did);g.s.commit()
        return send_file(storage.resolve(path),as_attachment=True,download_name=doc.key+('-reconstruido' if doc.source=='RECONSTRUCTED' and kind=='xml' else '')+'.'+kind)
    @app.post('/api/documents/<did>/retry')
    def retry(did):
        doc=document(did,True)
        if doc.xml:return jsonify(ok=True,message='XML já disponível; nenhuma conversão repetida.')
        job=g.s.scalar(select(Job).where(Job.document_id==did))
        if job and job.state=='running' and job.lease_until>time.time():raise FiscalError('Processamento em andamento. Aguarde a etapa atual.')
        if job:job.state='pending';job.attempts=0;job.available=time.time();job.owner=None;job.stage='conversion' if doc.pdf else 'lookup'
        else:g.s.add(Job(document_id=did,stage='conversion' if doc.pdf else 'lookup'))
        doc.status='aguardando';doc.error='';audit('reprocessamento_solicitado',doc.company_id,doc=did);g.s.commit();return jsonify(ok=True)
    @app.post('/api/documents/<did>/delete')
    def delete_doc(did):
        doc=document(did,True);company(doc.company_id,admin=True)
        verify_deletion_password(payload(),limited)
        # Match bulk deletion's lock order, so a worker cannot claim a removed job.
        jobs=g.s.scalars(select(Job).where(Job.document_id==did).order_by(Job.id).with_for_update()).all()
        if any(job.state=='running' for job in jobs):
            raise FiscalError('Há processamento em andamento. Aguarde sua conclusão antes de excluir.')
        doc=g.s.scalar(select(Document).where(Document.id==did).with_for_update().execution_options(populate_existing=True))
        if not doc:raise FiscalError('Documento não encontrado.')
        audit('documento_excluido',doc.company_id,doc=did)
        g.s.execute(delete(Job).where(Job.document_id==did));g.s.delete(doc);g.s.commit()
        # content-addressed objects retained until explicit maintenance/retention, to allow restore.
        return jsonify(ok=True,message='Registro removido. Arquivos seguem a política de retenção do administrador.')
    def export_path(name):
        path=storage.resolve(name)
        if not path.is_file():raise FiscalError('Arquivo XML ausente no armazenamento. Restaure o backup ou importe novamente antes de exportar.')
        return path
    @app.post('/api/export')
    def export():
        d=payload();cid=d.get('company');company(cid);ids=d.get('ids',[])
        if not isinstance(ids,list) or not 1<=len(ids)<=500 or any(not isinstance(x,str) or not x or len(x)>64 for x in ids):raise FiscalError('Selecione de 1 a 500 documentos válidos por ZIP.')
        docs=g.s.scalars(select(Document).where(Document.company_id==cid,Document.id.in_(ids))).all()
        if len(docs)!=len(set(ids)):raise FiscalError('Seleção contém documento indisponível.')
        if any(x.source=='RECONSTRUCTED' and x.status!='concluido' for x in docs):raise FiscalError('Seleção contém reconstrução pendente de conferência.')
        if any(not x.xml for x in docs):raise FiscalError('Seleção contém documento sem XML.')
        if any(x.source=='RECONSTRUCTED' for x in docs) and d.get('include_reconstructed') is not True:raise FiscalError('Confirme a inclusão dos XMLs reconstruídos, que não são originais autorizados.')
        paths={x.id:export_path(x.xml) for x in docs}
        size=sum(path.stat().st_size for path in paths.values())
        if size>64*1024*1024:raise FiscalError('Divida a exportação em lotes menores que 64 MB.')
        buf=io.BytesIO();manifest=[]
        with zipfile.ZipFile(buf,'w',zipfile.ZIP_DEFLATED) as z:
            for doc in docs:
                data=json.loads(doc.data);folder='reconstruidos' if doc.source=='RECONSTRUCTED' else 'importados'
                z.write(paths[doc.id],folder+'/'+doc.key+'.xml')
                manifest.append({'key':doc.key,'source':doc.source,'sha256':data['sha256'],'schema':data['schema_status'],'signature':data['signature_validation'],'flow':data['flow'],'tare':None,'tax_credit':None})
                audit('xml_exportado',cid,doc=doc.id)
            z.writestr('manifesto.json',json.dumps(manifest,ensure_ascii=False,indent=2))
        g.s.commit();buf.seek(0);return send_file(buf,mimetype='application/zip',as_attachment=True,download_name='DocPronto-XMLs.zip')
    @app.post('/api/export/all')
    def export_all():
        import tempfile
        d=payload();cid=d.get('company');company(cid)
        include=d.get('include_reconstructed') is True
        stmt=select(Document).where(Document.company_id==cid,Document.xml.is_not(None))
        stmt=stmt.where(or_(Document.source!='RECONSTRUCTED',Document.status=='concluido'))
        if not include:stmt=stmt.where(Document.source!='RECONSTRUCTED')
        if d.get('source') in ('IMPORTED','RECONSTRUCTED'):stmt=stmt.where(Document.source==d['source'])
        buf=tempfile.TemporaryFile(dir=storage.root);count=0;size=0
        try:
            with zipfile.ZipFile(buf,'w',zipfile.ZIP_DEFLATED,allowZip64=True) as z:
                with tempfile.TemporaryFile(mode='w+t',encoding='utf-8',dir=storage.root) as manifest:
                    for doc in g.s.scalars(stmt.order_by(Document.id).execution_options(yield_per=100)):
                        path=export_path(doc.xml);size+=path.stat().st_size
                        if size>1024**3:raise FiscalError('Exportação excede 1 GB. Exporte seleções menores.')
                        folder='reconstruidos' if doc.source=='RECONSTRUCTED' else 'importados'
                        z.write(path,folder+'/'+doc.key+'.xml')
                        manifest.write(json.dumps({'key':doc.key,'source':doc.source,'sha256':hashlib.sha256(path.read_bytes()).hexdigest()})+'\n');count+=1
                    if not count:raise FiscalError('Nenhum XML elegível para exportação.')
                    manifest.seek(0)
                    with z.open('manifesto.jsonl','w') as target:
                        for line in manifest:target.write(line.encode())
            audit('xml_exportacao_completa',cid,json.dumps({'count':count,'bytes':size}));g.s.commit()
            buf.seek(0)
            response=send_file(buf,mimetype='application/zip',as_attachment=True,download_name='DocPronto-Todos-XMLs.zip')
            response.call_on_close(buf.close)
            return response
        except Exception:
            buf.close();raise
    @app.post('/api/rejections')
    def rejections():
        cid=request.form.get('company');company(cid);f=request.files.get('file')
        if not f:raise FiscalError('Selecione CSV de rejeições.')
        result=reconciliation_csv(f.read());audit('rejeicoes_analisadas',cid,str(len(result)));g.s.commit();return jsonify(items=result)
    @app.get('/api/audit')
    def audit_list():
        cid=request.args.get('company');company(cid,admin=True)
        rows=g.s.scalars(select(Audit).where(Audit.company_id==cid).order_by(Audit.created.desc()).limit(200))
        return jsonify([{'action':x.action,'details':x.details,'document_id':x.document_id,'created':x.created} for x in rows])
    @app.get('/api/integrations')
    def integrations():
        return jsonify(fsist={'status':'MANUAL','url':'https://www.fsist.com.br/','message':'Fluxo gratuito, uma chave por vez. Automação de lote pendente de documentação/autorização.'},docpronto={'status':'ADAPTER_CONFIGURADO' if os.getenv('DOCPRONTO_ADAPTER_COMMAND') else 'MOTOR_LOCAL','message':'Leitura PDF/OCR e reconstrução local com conferência em formulário. Adaptador externo opcional.'},a1={'status':'TESTE_DISPONIVEL'},a3={'status':'AGENTE_WINDOWS','message':'Requer token/cartão, driver do fabricante e agente instalado.'},xsd={'status':'CONFIGURADO' if os.getenv('NFE_XSD_PATH') else 'NAO_CONFIGURADO'})
    @app.post('/api/certificates/a1/test')
    def test_a1():
        if g.user.role!='superadmin':return fail('Somente administrador.',403)
        if not testing and not secure and request.host.split(':')[0] not in ('localhost','127.0.0.1'):return fail('A1 exige HTTPS ou acesso local.',403)
        f=request.files.get('file')
        if not f:raise FiscalError('Selecione certificado .pfx/.p12.')
        result=inspect_a1(f.read(256001),request.form.get('password',''));audit('a1_teste_posse');g.s.commit();return jsonify(result)
    @app.get('/api/queue')
    def queue_status():
        cid=request.args.get('company');company(cid)
        counts=dict(g.s.execute(select(Job.state,func.count()).join(Document,Document.id==Job.document_id).where(Document.company_id==cid).group_by(Job.state)).all())
        setting=g.s.get(Setting,'pause:'+cid)
        return jsonify(counts=counts,paused=bool(setting and setting.value=='1'))
    @app.post('/api/queue')
    def queue_control():
        d=payload();cid=d.get('company');company(cid,True);action=d.get('action')
        if action not in ('pause','resume','cancel'):raise FiscalError('Ação inválida.')
        key='pause:'+cid;setting=g.s.get(Setting,key)
        if not setting:setting=Setting(key=key,value='0');g.s.add(setting)
        setting.value='1' if action=='pause' else '0'
        if action=='cancel':
            docids=select(Document.id).where(Document.company_id==cid,Document.xml.is_(None))
            g.s.execute(update(Job).where(Job.document_id.in_(docids)).values(state='cancelled',owner=None,lease_until=0))
            g.s.execute(update(Document).where(Document.company_id==cid,Document.xml.is_(None)).values(status='cancelado',version=Document.version+1))
        audit('fila_'+action,cid);g.s.commit();return jsonify(ok=True)
    @app.get('/api/review/spec')
    def review_spec_route():
        from .pdf_engine import review_spec
        return jsonify(fields=review_spec())
    def persist_draft(doc,invoice):
        from .pdf_engine import validate_review
        if not isinstance(invoice,dict) or invoice.get('key')!=doc.key:raise FiscalError('Chave do rascunho diverge do documento.')
        if len(json.dumps(invoice))>1000000:raise FiscalError('Rascunho acima de 1 MB.')
        previous=json.loads(storage.resolve(doc.draft).read_text()) if doc.draft else {}
        def leaves(value,path=''):
            out={}
            if isinstance(value,dict):
                for k,v in value.items():out.update(leaves(v,(path+'.'+k).strip('.')))
            elif isinstance(value,list):
                for i,v in enumerate(value):out.update(leaves(v,path+'.'+str(i)))
            else:out[path]=value
            return out
        old=leaves(previous.get('invoice',{}));new=leaves(invoice);evidence=previous.setdefault('evidence',{})
        for path in old.keys()|new.keys():
            if old.get(path)!=new.get(path):
                entry={'source':'user_review','method':'manual_edit','reviewed_at':time.time(),'user_id':g.user.id}
                if path in evidence:entry['original_evidence']=evidence[path] if evidence[path].get('source')!='user_review' else evidence[path].get('original_evidence')
                evidence[path]=entry
        previous['invoice']=invoice;previous['missing']=validate_review(invoice)
        previous['last_reviewed_at']=time.time()
        doc.draft=storage.save(doc.company_id,doc.id,json.dumps(previous,ensure_ascii=False).encode(),'json')
        doc.status='revisao';doc.updated=time.time();audit('rascunho_salvo',doc.company_id,doc=doc.id)
        return previous
    @app.post('/api/documents/<did>/draft')
    def save_draft(did):
        doc=document(did,True)
        if doc.xml:raise FiscalError('XML já gerado. Original preservado.')
        previous=persist_draft(doc,payload().get('invoice'));g.s.commit()
        return jsonify(ok=True,missing=previous['missing'])
    def ingest_pdf(raw,cid,key_hint=None):
        from .pdf_engine import extract_invoice
        import tempfile
        company(cid,True);validate_pdf(raw)
        with tempfile.TemporaryDirectory() as directory:
            p=Path(directory)/'input.pdf';p.write_bytes(raw);extracted=extract_invoice(p,key_hint)
        key=validate_key(extracted['invoice'].get('key'))
        doc=g.s.scalar(select(Document).where(Document.company_id==cid,Document.key==key))
        if not doc:doc=Document(id=uid(),company_id=cid,key=key);g.s.add(doc);g.s.flush()
        if doc.pdf:
            if hashlib.sha256(storage.resolve(doc.pdf).read_bytes()).digest()!=hashlib.sha256(raw).digest():raise FiscalError('Já há PDF diferente para esta chave. Original preservado.')
            return {'id':doc.id,'key':key,'duplicate':True}
        doc.pdf=storage.save(cid,doc.id,raw,'pdf');doc.draft=storage.save(cid,doc.id,json.dumps(extracted,ensure_ascii=False).encode(),'json');doc.updated=time.time()
        if not doc.xml:
            doc.status='revisao';job=g.s.scalar(select(Job).where(Job.document_id==doc.id))
            if job:job.state='pending';job.stage='conversion';job.attempts=0;job.available=time.time();job.owner=None
            else:g.s.add(Job(document_id=doc.id,stage='conversion'))
        audit('pdf_importado',cid,hashlib.sha256(raw).hexdigest(),doc.id)
        return {'id':doc.id,'key':key,'missing':extracted['missing']}
    @app.post('/api/pdf/import')
    def import_pdf_batch():
        cid=request.form.get('company');company(cid,True);files=request.files.getlist('files')
        if not 1<=len(files)<=20:raise FiscalError('Selecione de 1 a 20 PDFs por envio; a pasta monitorada aceita lotes contínuos.')
        results=[]
        for file in files:
            try:
                raw=file.read(20*1024*1024+1)
                if len(raw)>20*1024*1024:raise FiscalError('PDF excede 20 MB.')
                with g.s.begin_nested():result=ingest_pdf(raw,cid,request.form.get('key') or None)
                g.s.commit();results.append({'file':file.filename,**result})
            except (FiscalError,ValueError,ProviderPending,ProviderFailure) as ex:
                g.s.rollback();results.append({'file':file.filename,'error':str(ex)})
        return jsonify(results=results)
    def agent_ingest(device,raw,filename,target_company_id=None):
        target_company_id=target_company_id or device.company_id
        if not device_allowed(g.s,device,target_company_id):
            raise FiscalError('Computador não vinculado à empresa de destino.')
        g.user=g.s.get(User,device.created_by)
        if not g.user:raise FiscalError('Administrador do agente indisponível.')
        if raw.startswith(b'%PDF-'):
            hint=re.search(r'(?<!\d)(\d{44})(?!\d)',filename)
            return ingest_pdf(raw,target_company_id,hint.group(1) if hint else None)
        result=ingest_xml(raw,target_company_id,'auto')
        doc=g.s.get(Document,result['id']);return {'id':doc.id,'key':doc.key}
    @app.get('/api/agent-installer')
    def agent_installer():
        path=Path(__file__).resolve().parent.parent/'agent-windows'/'DocPronto-Instalar.exe'
        if not path.is_file():raise FiscalError('Instalador do conector indisponível neste pacote.')
        return send_file(path,as_attachment=True,download_name=path.name)
    @app.get('/api/agent-download')
    def agent_download():
        path=Path(__file__).resolve().parent.parent/'agent-windows'/'DocPronto-Instalar.exe'
        if not path.is_file():raise FiscalError('Pacote do agente não está instalado no servidor. Atualize a instalação.')
        return send_file(path,as_attachment=True,download_name=path.name)
    register_distribution(app,company,agent_ingest,storage)
    register_agent_bridge(app,company,agent_ingest,limited)
    register_management(app,company,payload,limited)
    from .local_maintenance import register_local_maintenance
    register_local_maintenance(app)
    from .local_backups_api import register_local_backups
    register_local_backups(app)
    from .local_network import register_local_network
    register_local_network(app)
    from .diagnostics import register_diagnostics
    register_diagnostics(app,company)
    from .capture_preflight import register_capture_preflight
    register_capture_preflight(app,company)
    from .teams import register_teams
    register_teams(app,limited,secure)
    register_history(app,company,storage,limited)
    from .fiscal_sources import register_fiscal_sources
    register_fiscal_sources(app,company,storage)
    register_client_capture(app,company,storage)
    register_fiscal_channels(app,company)
    register_nfce(app,company,storage)
    from .overview import register_overview
    register_overview(app)
    from .appearance import register_appearance
    register_appearance(app)
    return app
